source 'https://rubygems.org'
#
# jekyll-assets plugin itself
#

gem "jekyll-assets"
#
# Additional gems for jekyll-assets
#

gem "uglifier"      # And we want our javascripts to be minified with UglifyJS
gem 'sass'
gem "bourbon"
